# Generated by Django 3.2.13 on 2022-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlelog',
            name='log',
            field=models.CharField(max_length=10),
        ),
    ]
