# Generated by Django 3.2.13 on 2022-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_alter_battlelog_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
