# Generated by Django 3.2.13 on 2022-11-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blackcude',
            new_name='blackcube',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='redcude',
            new_name='redcube',
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(default='Bronze', max_length=20),
        ),
    ]
